name: dataclass
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 1.0.0
repository: https://github.com/rrousselGit/freezed
issue_tracker: https://github.com/rrousselGit/freezed/issues

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  collection: ^1.19.1
  macros: ^0.1.3-main.0
  meta: ^1.15.0
dev_dependencies:
  analyzer: ^7.2.0
  build_test: ^2.2.3
  test: ^1.25.5
